version: "3.7"
services:
  rtmp:
    image: tiangolo/nginx-rtmp:latest-2026-02-09
    container_name: rtmp
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    environment:
      PUID: 1000
      PGID: 1000
      TZ: US/Eastern 
    ports:
      - 1935:1935      # RTMP ingest
      - 8088:80        # HTTP out (player + HLS)
    restart: unless-stopped  
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - /home/lancer1977/servers/rtmp/hls:/var/www/hls
      - ./html:/var/www/html:ro
